install: Add assertion on source file path

diff --git a/install b/install
--- a/install
+++ b/install
@@ -36,6 +36,11 @@ run() {
 
 put() {
 	local src="$SRC_DIR/$1"
+	if ! [ -f "$src" ]; then
+		printf "error: source file '%s' does not exist\n" "$src" >&2
+		exit 1
+	fi
+
 	local dest="$2"
 	local dest_dir
 	dest_dir="$(dirname "$dest")"
